#ifndef __TEXTURES_H__
#define __TEXTURES_H__

enum
{
	TEXTURE_ASTEROID1,
	TEXTURE_ASTEROID1_NORMAL,
	TEXTURE_ASTEROID2,
	TEXTURE_ASTEROID2_NORMAL,
	TEXTURE_ASTEROID3,
	TEXTURE_ASTEROID3_NORMAL,
	TEXTURE_ASTEROID4,
	TEXTURE_ASTEROID4_NORMAL,
	NUM_TEXTURES
};

extern VkuImage_t Textures[NUM_TEXTURES];

#endif
