set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(TARGET_TRIPLE x86_64-w64-mingw32ucrt)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

set(CMAKE_C_COMPILER_TARGET ${TARGET_TRIPLE})
set(CMAKE_CXX_COMPILER_TARGET ${TARGET_TRIPLE})
set(CMAKE_RC_COMPILER_TARGET ${TARGET_TRIPLE})

set(CMAKE_C_FLAGS "-fuse-ld=lld -DWINAPI_PARTITION_SYSTEM=WINAPI_PARTITION_DESKTOP")
set(CMAKE_CXX_FLAGS ${CMAKE_C_FLAGS})

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-subsystem,windows -static")

set(VULKAN_SDK "/opt/VulkanSDK/1.4.341.1")
set(CMAKE_INCLUDE_PATH "${VULKAN_SDK}/Include")
set(CMAKE_LIBRARY_PATH "${VULKAN_SDK}/Lib")
